"""Constants for open3e."""

DOMAIN = "open3e"

CONNECTION_MODE_KEY = "connection_mode"
CONNECTION_MODE_CLASSIC = "classic"
CONNECTION_MODE_WEBUI = "webui"
CONNECTION_MODE_DEFAULT = CONNECTION_MODE_WEBUI

MQTT_TOPIC_KEY = "mqtt_topic"
MQTT_TOPIC_DEFAULT = "open3e_develop"
MQTT_CMD_KEY = "mqtt_cmnd"
MQTT_CMD_DEFAULT = "open3e_develop/cmnd"
MQTT_DISCOVERY_PREFIX_KEY = "mqtt_discovery_prefix"
MQTT_DISCOVERY_PREFIX_DEFAULT = "homeassistant"
MQTT_SYSTEM_TOPIC = "system"
MQTT_SYSTEM_PAYLOAD = '{"mode":"system"}'

VIESSMANN_TEMP_HEATING_MIN = 3
VIESSMANN_TEMP_HEATING_MAX = 37

VIESSMANN_TEMP_DHW_MIN = 10
VIESSMANN_TEMP_DHW_MAX = 60

VIESSMANN_POWER_MAX_WATT_ELECTRICAL_HEATER = 8000
VIESSMANN_POWER_MIN_WATT_ELECTRICAL_HEATER = 0
VIESSMANN_POWER_WATT_ELECTRICAL_HEATER_STEP = 1000

VIESSMANN_SMART_GRID_TEMP_MIN = 0
VIESSMANN_SMART_GRID_TEMP_MAX = 20

VIESSMANN_HYSTERESIS_MIN = 0
VIESSMANN_HYSTERESIS_MAX = 10

VIESSMANN_UNAVAILABLE_VALUE = -3276.8
VITODENS_UNAVAILABLE_VALUE = 127
