from dataclasses import dataclass


@dataclass(frozen=True)
class Feature:
    id: int
    """The ID used on the Open3e server to identify the feature."""
    refresh_interval: int | None
    """Represent the refresh interval in seconds.
    The minimum and step size is 5 seconds.

    If its set to None, the feature will not be refreshed and only be used for setting data.
    """


class Features:
    class Temperature:
        Flow = Feature(id=268, refresh_interval=5)
        Return = Feature(id=269, refresh_interval=5)
        DomesticHotWater = Feature(id=271, refresh_interval=5)
        DomesticHotWaterTarget = Feature(id=396, refresh_interval=300)
        Outside = Feature(id=274, refresh_interval=5)
        FlowCircuit1 = Feature(id=284, refresh_interval=5)
        FlowCircuit2 = Feature(id=286, refresh_interval=5)
        FlowCircuit3 = Feature(id=288, refresh_interval=5)
        FlowCircuit4 = Feature(id=290, refresh_interval=5)
        FlowCircuit1Target = Feature(id=987, refresh_interval=30)
        FlowCircuit2Target = Feature(id=988, refresh_interval=30)
        FlowCircuit3Target = Feature(id=989, refresh_interval=30)
        FlowCircuit4Target = Feature(id=990, refresh_interval=30)
        PrimaryHeatExchanger = Feature(id=320, refresh_interval=5)
        CompressorInlet = Feature(id=321, refresh_interval=5)
        CompressorOutlet = Feature(id=324, refresh_interval=5)
        Room1 = Feature(id=334, refresh_interval=5)
        Room2 = Feature(id=335, refresh_interval=5)
        Room3 = Feature(id=336, refresh_interval=5)
        Room4 = Feature(id=337, refresh_interval=5)
        RoomCurrentValue1 = Feature(id=1886, refresh_interval=30)
        RoomCurrentValue2 = Feature(id=1889, refresh_interval=30)
        RoomCurrentValue3 = Feature(id=1892, refresh_interval=30)
        RoomCurrentValue4 = Feature(id=1895, refresh_interval=30)
        RoomCurrentValue5 = Feature(id=1898, refresh_interval=30)
        RoomCurrentValue6 = Feature(id=1901, refresh_interval=30)
        RoomCurrentValue7 = Feature(id=1904, refresh_interval=30)
        RoomCurrentValue8 = Feature(id=1907, refresh_interval=30)
        RoomCurrentValue9 = Feature(id=1910, refresh_interval=30)
        RoomCurrentValue10 = Feature(id=1913, refresh_interval=30)
        RoomCurrentValue11 = Feature(id=1916, refresh_interval=30)
        RoomCurrentValue12 = Feature(id=1919, refresh_interval=30)
        RoomCurrentValue13 = Feature(id=1922, refresh_interval=30)
        RoomCurrentValue14 = Feature(id=1925, refresh_interval=30)
        RoomCurrentValue15 = Feature(id=1928, refresh_interval=30)
        RoomCurrentValue16 = Feature(id=1931, refresh_interval=30)
        RoomCurrentValue17 = Feature(id=1934, refresh_interval=30)
        RoomCurrentValue18 = Feature(id=1937, refresh_interval=30)
        RoomCurrentValue19 = Feature(id=1940, refresh_interval=30)
        RoomCurrentValue20 = Feature(id=1943, refresh_interval=30)
        SecondaryHeatExchanger = Feature(id=355, refresh_interval=5)
        ProgramsCircuit1 = Feature(id=424, refresh_interval=30)
        ProgramsCircuit2 = Feature(id=426, refresh_interval=30)
        ProgramsCircuit3 = Feature(id=428, refresh_interval=30)
        ProgramsCircuit4 = Feature(id=430, refresh_interval=30)
        CoolingProgramsCircuit1 = Feature(id=2546, refresh_interval=30)
        CoolingProgramsCircuit2 = Feature(id=2547, refresh_interval=30)
        CoolingProgramsCircuit3 = Feature(id=2548, refresh_interval=30)
        CoolingProgramsCircuit4 = Feature(id=2549, refresh_interval=30)
        PrimaryInlet = Feature(id=1769, refresh_interval=5)
        SecondaryOutlet = Feature(id=1769, refresh_interval=5)
        EngineRoom = Feature(id=1771, refresh_interval=30)
        CompressorOil = Feature(id=1772, refresh_interval=30)
        EconomizerLiquid = Feature(id=2333, refresh_interval=30)
        EvaporationVapor = Feature(id=2334, refresh_interval=30)
        SmartGridTemperatureOffsets = Feature(id=2543, refresh_interval=5)
        FlowCircuit1Cooling = Feature(id=2405, refresh_interval=30)
        FlowCircuit2Cooling = Feature(id=2406, refresh_interval=30)
        FlowCircuit3Cooling = Feature(id=2407, refresh_interval=30)
        FlowCircuit4Cooling = Feature(id=2408, refresh_interval=30)
        FlowCircuit1CoolingHysteresis = Feature(id=2413, refresh_interval=30)
        FlowCircuit2CoolingHysteresis = Feature(id=2414, refresh_interval=30)
        FlowCircuit3CoolingHysteresis = Feature(id=2415, refresh_interval=30)
        FlowCircuit4CoolingHysteresis = Feature(id=2416, refresh_interval=30)
        BufferMinMax = Feature(id=3106, refresh_interval=30)
        OutdoorAir = Feature(id=327, refresh_interval=5)
        SupplyAir = Feature(id=328, refresh_interval=5)
        ExtractAir = Feature(id=329, refresh_interval=5)
        ExhaustAir = Feature(id=330, refresh_interval=5)
        InverterAmbient = Feature(id=1684, refresh_interval=30)
        Battery = Feature(id=2240, refresh_interval=30)
        HeatingBuffer = Feature(id=3016, refresh_interval=30)
        CoolingBuffer = Feature(id=3017, refresh_interval=30)
        HeatingCoolingBuffer = Feature(id=3018, refresh_interval=30)
        DhwBufferBottom = Feature(id=3232, refresh_interval=30)
        DhwBufferMid = Feature(id=3233, refresh_interval=30)
        DhwBufferTop = Feature(id=3234, refresh_interval=30)
        DomesticHotWaterHysteresis = Feature(id=1085, refresh_interval=30)

        # Vitodens
        FlowTemperatureSensor = Feature(id=268, refresh_interval=30)
        DomesticHotWaterSensor = Feature(id=271, refresh_interval=30)
        OutsideTemperatureSensor = Feature(id=274, refresh_interval=30)
        MixerOneCircuitFlowTemperatureSensor = Feature(id=284, refresh_interval=30)
        MixerTwoCircuitFlowTemperatureSensor = Feature(id=286, refresh_interval=30)
        MixerThreeCircuitFlowTemperatureSensor = Feature(id=288, refresh_interval=30)
        MixerFourCircuitFlowTemperatureSensor = Feature(id=290, refresh_interval=30)
        FlueGasTemperatureSensor = Feature(id=331, refresh_interval=10)
        MixerOneCircuitRoomTemperatureSensor = Feature(id=334, refresh_interval=10)
        MixerTwoCircuitRoomTemperatureSensor = Feature(id=335, refresh_interval=10)
        MixerThreeCircuitRoomTemperatureSensor = Feature(id=336, refresh_interval=10)
        MixerFourCircuitRoomTemperatureSensor = Feature(id=337, refresh_interval=10)
        DomesticHotWaterOutletSensor = Feature(id=360, refresh_interval=10)
        DomesticHotWaterTemperatureSetpoint = Feature(id=396, refresh_interval=30)
        MixerOneCircuitRoomTemperatureSetpoint = Feature(id=424, refresh_interval=60)
        MixerTwoCircuitRoomTemperatureSetpoint = Feature(id=426, refresh_interval=60)
        MixerThreeCircuitRoomTemperatureSetpoint = Feature(id=428, refresh_interval=60)
        MixerFourCircuitRoomTemperatureSetpoint = Feature(id=430, refresh_interval=60)
        FlowTemperatureTargetSetpoint = Feature(id=527, refresh_interval=30)
        MixerOneCircuitFlowTemperatureTargetSetpoint = Feature(id=987, refresh_interval=30)
        MixerTwoCircuitFlowTemperatureTargetSetpoint = Feature(id=988, refresh_interval=30)
        MixerThreeCircuitFlowTemperatureTargetSetpoint = Feature(id=989, refresh_interval=30)
        MixerFourCircuitFlowTemperatureTargetSetpoint = Feature(id=990, refresh_interval=30)

        # Soll-/Min-/Max-Temperaturen
        MixerOneCircuitFlowTemperatureMinimumMaximumLimit = Feature(id=1192, refresh_interval=300)
        MixerTwoCircuitFlowTemperatureMinimumMaximumLimit = Feature(id=1193, refresh_interval=300)
        MixerOneCircuitCurrentTemperatureSetpoint = Feature(id=1643, refresh_interval=30)
        MixerTwoCircuitCurrentTemperatureSetpoint = Feature(id=1644, refresh_interval=30)

    class Humidity:
        Outdoor = Feature(id=419, refresh_interval=5)
        SupplyAir = Feature(id=420, refresh_interval=5)
        ExtractAir = Feature(id=421, refresh_interval=5)
        ExhaustAir = Feature(id=422, refresh_interval=5)

    class Pressure:
        Water = Feature(id=318, refresh_interval=15)
        CompressorInlet = Feature(id=322, refresh_interval=15)
        CompressorOutlet = Feature(id=325, refresh_interval=15)

        # Vitodens
        WaterPressureSensor = Feature(id=318, refresh_interval=10)

    class Energy:
        CentralHeating = Feature(id=548, refresh_interval=300)
        DomesticHotWater = Feature(id=565, refresh_interval=300)
        Cooling = Feature(id=566, refresh_interval=300)
        Battery = Feature(id=1801, refresh_interval=300)
        PV = Feature(id=1802, refresh_interval=300)
        PVStringVoltage = Feature(id=1833, refresh_interval=300)
        Grid = Feature(id=535, refresh_interval=300)
        HeatingOutput = Feature(id=1211, refresh_interval=30)
        WarmWaterOutput = Feature(id=1391, refresh_interval=30)
        CoolingOutput = Feature(id=2529, refresh_interval=30)
        DesiredThermalCapacity = Feature(id=2629, refresh_interval=30)
        DesiredThermalEnergyDefrost = Feature(id=2256, refresh_interval=30)
        Cop = Feature(id=2625, refresh_interval=300)
        CopHeating = Feature(id=2622, refresh_interval=300)
        CopDhw = Feature(id=2624, refresh_interval=300)
        EnergyOwnConsumption = Feature(id=2760, refresh_interval=300)

        # Vitodens
        EnergyConsumptionCentralHeating = Feature(id=548, refresh_interval=60)
        EnergyConsumptionDomesticHotWater = Feature(id=565, refresh_interval=60)
        GeneratedCentralHeatingOutput = Feature(id=1211, refresh_interval=60)
        EnergyConsumptionCentralHeatingMonthMatrix = Feature(id=1294, refresh_interval=60)
        EnergyConsumptionDomesticHotWaterMonthMatrix = Feature(id=1311, refresh_interval=60)
        GeneratedCentralHeatingOutputMonthMatrix = Feature(id=1315, refresh_interval=60)
        EnergyConsumptionCentralHeatingYearMatrix = Feature(id=1316, refresh_interval=60)
        EnergyConsumptionDomesticHotWaterYearMatrix = Feature(id=1333, refresh_interval=60)
        GeneratedCentralHeatingOutputYearMatrix = Feature(id=1337, refresh_interval=60)
        GeneratedDomesticHotWaterOutput = Feature(id=1391, refresh_interval=60)
        GeneratedDomesticHotWaterOutputMonthMatrix = Feature(id=1392, refresh_interval=60)
        GeneratedDomesticHotWaterOutputYearMatrix = Feature(id=1393, refresh_interval=60)

    class Power:
        Fan1 = Feature(id=1775, refresh_interval=5)
        Fan2 = Feature(id=1776, refresh_interval=5)
        RefrigerantCircuit = Feature(id=2486, refresh_interval=5)
        ElectricalHeater = Feature(id=2487, refresh_interval=5)
        System = Feature(id=2488, refresh_interval=5)
        ThermalCapacitySystem = Feature(id=2496, refresh_interval=5)
        Battery = Feature(id=1836, refresh_interval=5)
        PV = Feature(id=1690, refresh_interval=5)
        BatteryCurrent = Feature(id=1837, refresh_interval=5)
        BatteryVoltage = Feature(id=1838, refresh_interval=5)
        MaxElectricalHeater = Feature(id=2626, refresh_interval=5)
        Grid = Feature(id=1603, refresh_interval=5)

    class State:
        HvacCircuit1 = Feature(id=1415, refresh_interval=30)
        HvacCircuit2 = Feature(id=1416, refresh_interval=30)
        HvacCircuit3 = Feature(id=1417, refresh_interval=30)
        HvacCircuit4 = Feature(id=1418, refresh_interval=30)
        AdditionalHeater = Feature(id=2352, refresh_interval=30)
        DomesticHotWater = Feature(id=531, refresh_interval=30)
        DomesticHotWaterEfficiency = Feature(id=3029, refresh_interval=30)
        Battery = Feature(id=1664, refresh_interval=30)
        BackUpBox = Feature(id=2214, refresh_interval=30)
        BatteryStateOfEnergy = Feature(id=1834, refresh_interval=30)
        MaximumRechargePower = Feature(id=2643, refresh_interval=30)
        Allengra = Feature(id=1043, refresh_interval=30)
        HeatPumpCompressor = Feature(id=2351, refresh_interval=30)
        Buffer = Feature(id=3070, refresh_interval=30)
        CircuitFrostProtection = Feature(id=2855, refresh_interval=30)
        CentralHeatingPump = Feature(id=381, refresh_interval=10)
        Circuit1Pump = Feature(id=401, refresh_interval=10)
        Circuit2Pump = Feature(id=402, refresh_interval=10)
        Circuit3Pump = Feature(id=403, refresh_interval=10)
        Circuit4Pump = Feature(id=404, refresh_interval=10)
        HotWaterCirculationPump = Feature(id=491, refresh_interval=30)
        DomesticHotWaterCirculationPumpMode = Feature(id=497, refresh_interval=30)
        TargetQuickMode = Feature(id=1006, refresh_interval=30)
        CurrentQuickMode = Feature(id=1007, refresh_interval=30)
        FrostProtection = Feature(id=2489, refresh_interval=30)
        EnergyManagement = Feature(id=2350, refresh_interval=30)
        FlowCircuit1HeatingCurve = Feature(id=880, refresh_interval=30)
        FlowCircuit2HeatingCurve = Feature(id=881, refresh_interval=30)
        FlowCircuit3HeatingCurve = Feature(id=882, refresh_interval=30)
        FlowCircuit4HeatingCurve = Feature(id=883, refresh_interval=30)
        VentilationMode = Feature(id=2371, refresh_interval=30)
        VentilationLevel = Feature(id=533, refresh_interval=30)
        BypassOperationState = Feature(id=437, refresh_interval=30)
        BypassAvailableModes = Feature(id=439, refresh_interval=30)
        OutsideAirBypass = Feature(id=1088, refresh_interval=30)
        InsideAirBypass = Feature(id=1089, refresh_interval=30)
        BypassOperationLevel = Feature(id=2403, refresh_interval=30)
        # ToDo: Not yet in Open3e server (still raw hex)
        # VentilationBypassPosition = Feature(id=2493, refresh_interval=30)
        VentilationBypassFlapAvailableCount = Feature(id=2797, refresh_interval=30)

        # Pump-Status und Kältekreis
        CentralHeatingPumpStatus = Feature(id=2791, refresh_interval=10)
        MixerOneCircuitPumpStatus = Feature(id=2792, refresh_interval=10)
        MixerTwoCircuitPumpStatus = Feature(id=2793, refresh_interval=10)
        RefrigerationCircuitOperationMode = Feature(id=2806, refresh_interval=10)

        # Vitodens
        Flame = Feature(id=364, refresh_interval=10)
        DomesticHotWaterCirculationPump = Feature(id=491, refresh_interval=10)
        DomesticHotWaterOperationState = Feature(id=531, refresh_interval=10)
        LegionellaProtectionActivation = Feature(id=873, refresh_interval=60)
        MalfunctionHeatingUnitBlocked = Feature(id=1339, refresh_interval=10)
        MixerOneCircuitOperationState = Feature(id=1415, refresh_interval=10)
        MixerTwoCircuitOperationState = Feature(id=1416, refresh_interval=10)
        MixerThreeCircuitOperationState = Feature(id=1417, refresh_interval=10)
        MixerFourCircuitOperationState = Feature(id=1418, refresh_interval=10)

    class Volume:
        Ventilation = Feature(id=2328, refresh_interval=10)

        # Vitodens
        GasConsumptionCentralHeating = Feature(id=544, refresh_interval=60)
        GasConsumptionDomesticHotWater = Feature(id=545, refresh_interval=60)
        AllengraSensor = Feature(id=1043, refresh_interval=10)
        GasConsumptionCentralHeatingMonthMatrix = Feature(id=1342, refresh_interval=86400)
        GasConsumptionCentralHeatingYearMatrix = Feature(id=1343, refresh_interval=86400)
        GasConsumptionDomesticHotWaterMonthMatrix = Feature(id=1344, refresh_interval=86400)
        GasConsumptionDomesticHotWaterYearMatrix = Feature(id=1345, refresh_interval=86400)

    class Speed:
        CompressorPercent = Feature(id=2346, refresh_interval=10)
        CompressorRps = Feature(id=2569, refresh_interval=10)
        SupplyAirFan = Feature(id=1040, refresh_interval=10)
        ExhaustAirFan = Feature(id=1041, refresh_interval=10)
        Circuit1Pump = Feature(id=1102, refresh_interval=10)
        Circuit2Pump = Feature(id=1103, refresh_interval=10)
        Circuit3Pump = Feature(id=1104, refresh_interval=10)
        Circuit4Pump = Feature(id=1105, refresh_interval=10)

        # Pumpgeschwindigkeit WW
        DomesticHotWaterPumpMinimumLimit = Feature(id=1100, refresh_interval=300)
        DomesticHotWaterPumpMaximumLimit = Feature(id=1101, refresh_interval=300)

    class Position:
        ExpansionValve1 = Feature(id=389, refresh_interval=30)
        ExpansionValve2 = Feature(id=391, refresh_interval=30)
        FourThreeWayValve = Feature(id=2735, refresh_interval=30)

        # Mischer-Ventile
        MixerOneCircuitThreeWayValvePositionPercent = Feature(id=475, refresh_interval=30)
        MixerTwoCircuitThreeWayValvePositionPercent = Feature(id=476, refresh_interval=30)
        MixerThreeCircuitThreeWayValvePositionPercent = Feature(id=477, refresh_interval=30)
        MixerFourCircuitThreeWayValvePositionPercent = Feature(id=478, refresh_interval=30)

    class Time:
        Date = Feature(id=505, refresh_interval=60)
        Time = Feature(id=506, refresh_interval=60)
        OperatingHoursTillService = Feature(id=521, refresh_interval=60)
        ServiceDateNext = Feature(id=522, refresh_interval=60)
        LegionellaProtectionStartTime = Feature(id=875, refresh_interval=60)
        LegionellaProtectionWeekday = Feature(id=876, refresh_interval=60)
        LegionellaProtectionLastSuccessfulStartTime = Feature(id=877, refresh_interval=60)
        LegionellaProtectionLastSuccessfulWeekday = Feature(id=878, refresh_interval=60)
        HeatEngineStatistical = Feature(id=1346, refresh_interval=60)

    class Misc:
        CompressorStatistics = Feature(id=2369, refresh_interval=120)
        AdditionalHeaterStatistics = Feature(id=2370, refresh_interval=120)
        ServiceManagerIsRequired = Feature(id=901, refresh_interval=30)
        MalfunctionIdentification = Feature(id=902, refresh_interval=30)
        ErrorDtcList = Feature(id=265, refresh_interval=30)
        BackendConnectionStatus = Feature(id=1165, refresh_interval=30)

        # Vitodens
        StatusDtcList = Feature(id=257, refresh_interval=60)
        StatusDtcHistory = Feature(id=258, refresh_interval=60)
        InfoDtcList = Feature(id=259, refresh_interval=60)
        InfoDtcHistory = Feature(id=260, refresh_interval=60)
        ServiceDtcList = Feature(id=261, refresh_interval=60)
        ServiceDtcHistory = Feature(id=262, refresh_interval=60)
        WarningDtcList = Feature(id=263, refresh_interval=60)
        WarningDtcHistory = Feature(id=264, refresh_interval=60)
        ErrorDtcHistory = Feature(id=266, refresh_interval=60)
        ScaldProtection = Feature(id=503, refresh_interval=60)
        GatewayMac = Feature(id=593, refresh_interval=2592000)
        GatewayRemoteLocalNetworkStatus = Feature(id=602, refresh_interval=60)
        GatewayRemoteIp = Feature(id=607, refresh_interval=60)
        CentralHeatingOneCircuitName = Feature(id=627, refresh_interval=86400)
        CentralHeatingTwoCircuitName = Feature(id=628, refresh_interval=86400)
        CentralHeatingThreeCircuitName = Feature(id=629, refresh_interval=86400)
        CentralHeatingFourCircuitName = Feature(id=630, refresh_interval=86400)
        GatewayRemoteSignalStrength = Feature(id=900, refresh_interval=60)
        BuildingType = Feature(id=927, refresh_interval=2592000)
        ElectronicTraceabilityNumber = Feature(id=928, refresh_interval=2592000)
        GasType = Feature(id=929, refresh_interval=86400)
        CentralHeatingRegulationMode = Feature(id=1004, refresh_interval=3600)
        TimeSettingSource = Feature(id=1504, refresh_interval=86400)
        ChimneySweeperTestMode = Feature(id=1537, refresh_interval=30)
        SmartGridReadyConsolidator = Feature(id=543, refresh_interval=30)
        ExternalLockActive = Feature(id=1731, refresh_interval=30)
        DomesticHotWaterStatus = Feature(id=2320, refresh_interval=30)
        HeatPumpFrostProtection = Feature(id=2442, refresh_interval=300)
        EnableElectricalHeaterSmartGridMin = Feature(id=2544, refresh_interval=300)
        EnableElectricalHeaterSmartGridMax = Feature(id=2545, refresh_interval=300)
        SmartGridFeatureSelection = Feature(id=2560, refresh_interval=300)
        CompressorMinMaxSpeedHeating = Feature(id=2630, refresh_interval=300)
        NoiseReductionMode = Feature(id=2634, refresh_interval=300)
        MixerOneCircuitFrostProtectionConfiguration = Feature(id=2855, refresh_interval=300)
        MixerTwoCircuitFrostProtectionConfiguration = Feature(id=2856, refresh_interval=300)
